server:
    error:
        include-message: always
    port: 7001
logging:
    level:
        root: INFO
        com.example.GroceryStoreApp: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

# for docker

spring:
    datasource:
        url: jdbc:mysql://mysql2/customer-db
        username: user
        password: pwd


    jpa:
        hibernate:
            ddl-auto: none

    config:
        activate:
            on-profile: docker

    sql:
        init:
            platform: mysql
            mode: always


spring.datasource.hikari.initializationFailTimeout: 60000

---
# for test

#for h2
spring:
    config:
        activate:
            on-profile: h2

    h2:
        console:
            enabled: true

    datasource:
        url: jdbc:h2:mem:clients-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
        driver-class-name: org.h2.Driver
        username: sa
        password: pwd
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            #let jpa create the schema
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                auto-quote-keyword: true
        #Turn this on to ensure that hibernate initializes the schema before loading the data
        defer-datasource-initialization: true
    sql:
        init:
            platform: h2
            mode: always
