services:
  product-service:
    build: .
    hostname: product-service
    ports:
      - "7003:7003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  mysql3:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql3:/var/lib/mysql3
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdminProduct
    links:
      - mysql3
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1