server:
    error:
        include-message: always
    port: 7003
logging:
    level:
        root: INFO
        com.example.GroceryStoreApp: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

# for docker

spring:
    datasource:
        url: jdbc:mysql://mysql3/product-db
        username: user
        password: pwd

    jpa:
        hibernate:
            ddl-auto: none

    config:
        activate:
            on-profile: docker

    sql:
        init:
            platform: mysql
            mode: always

spring.datasource.hikari.initializationFailTimeout: 60000