@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for Grocery Store Application
Person(employee, "Employee", "Grocery Store Administrator")
Person(customer, "Customer", "Clients that are purchasing")
System(grocerystoreapp, "Grocery Store System", "Allows the Grocery Store Administrator to properly manage clients and transactions")

Rel(employee, grocerystoreapp, "Track and modify product price, clients files and employee status", "Uses")
Rel(customer, grocerystoreapp, "Make transactions", "Uses")

'SHOW_LEGEND()
@enduml