services:
  employee-service:
    build: .
    hostname: employee-service
    ports:
      - "7002:7002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  mysql2:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=customer-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql2:/var/lib/mysql2
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdminCustomer
    links:
      - mysql2
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1